### ISSUE TITLE
windows 安装依赖报错: nvidia-dali-cuda120 不支持windows

### ISSUE THREAD

**Issue by DM-NUM** [TongjiFinLab/CFGPT#6]
请教个问题，该项目是否可以在windows10中运行，我在pip install requirements 时，nvidia-dali-cuda120安装失效，查了文献发现该包不支持windows系统，所以请问该项目能否在windows10中运行。

**Comment by Jiangtong-Li** [comment]
抱歉，不能在windows里运行
