### ISSUE TITLE
BUG：lora训练时用deepspeed开启zero_optimization会导致模型保存为空

### ISSUE THREAD

**Issue by DragonMengLong** [TongjiFinLab/CFGPT#7]
作者自己重写了LoraTrainer中的_save方法，这个如果不开zero_optimization的时候是没有问题的，但是如果开zero_optimization会导致模型保存时实际保存内容为空，adapter没有从deepspeed框架中提取出来，训练log中会显示保存成功，但是重新load的时候会报错。这个问题之前在llama_factory中也出现过，[详见](https://github.com/hiyouga/LLaMA-Factory/issues/820#issue-1885199025)

**Comment by Jiangtong-Li** [comment]
感谢您的反馈，后续版本我们会修正这个问题。如果有微调需求，目前可以使用Xtune。
